### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by DarkShyMW** [DimiMikadze/orca#110]
i was install this script and when i run, take err:

```
darkshy@slainscraft:~/fs/bf$ npm start --unhandled-rejections=strict

> bf@1.0.0 start /home/darkshy/fs/bf
> concurrently "npm run start:api" "npm run start:frontend"

[0]
[0] > bf@1.0.0 start:api /home/darkshy/fs/bf
[0] > npm start --prefix api
[0]
[1]
[1] > bf@1.0.0 start:frontend /home/darkshy/fs/bf
[1] > npm start --prefix frontend
[1]
[1]
[1] > bf-frontend@1.0.0 start /home/darkshy/fs/bf/frontend
[1] > react-scripts start
[1]
[0]
[0] > bf-api@1.0.0 start /home/darkshy/fs/bf/api
[0] > nodemon index.js
[0]
[0] [nodemon] 2.0.7
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node index.js`
[1] ℹ ｢wds｣: Project is running at http://192.168.0.133/
[1] ℹ ｢wds｣: webpack output is served from
[1] ℹ ｢wds｣: Content not from webpack is served from /home/darkshy/fs/bf/frontend/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1]
[0] server ready at http://localhost:4000/graphql
[0] Subscriptions ready at ws://localhost:4000/graphql
[0] DB connected
[0] (node:72232) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/home/darkshy/fs/bf/api/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /home/darkshy/fs/bf/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/home/darkshy/fs/bf/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/home/darkshy/fs/bf/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/home/darkshy/fs/bf/api/node_modules/apollo-server-core/dist/ApolloServer.js:666:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/home/darkshy/fs/bf/api/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0] (Use `node --trace-warnings ...` to show where the warning was created)
[0] (node:72232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[0] (node:72232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] (node:72232) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/home/darkshy/fs/bf/api/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /home/darkshy/fs/bf/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/home/darkshy/fs/bf/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/home/darkshy/fs/bf/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/home/darkshy/fs/bf/api/node_modules/apollo-server-core/dist/ApolloServer.js:666:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/home/darkshy/fs/bf/api/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0] (node:72232) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by DarkShyMW** [comment]
![Uploading Снимок экрана (132).png…]()

**Comment by DarkShyMW** [comment]
![Снимок экрана (132)](https://user-images.githubusercontent.com/30442729/113595676-015fde00-9642-11eb-85c5-d3c1772bf598.png)

**Comment by DimiMikadze** [comment]
Hi, I'm closing this issue since we uploaded a new project to this repository. The old one is located here: https://github.com/DimiMikadze/create-social-network-old.
