### ISSUE TITLE
RangeError: Maximum call stack size exceeded error

### ISSUE THREAD

**Issue by maxx-abrt** [DimiMikadze/orca#122]
i get RangeError: Maximum call stack size exceeded error, i give you all the error :

RangeError: Maximum call stack size exceeded
    at ReadStream.open (C:\Users\maxau\OneDrive\Desktop\create-social-network-master\api\node_modules\@apollographql\graphql-upload-8-fork\node_modules\fs-capacitor\lib\index.js:80:7)
    at _openReadFs (internal/fs/streams.js:138:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (C:\Users\maxau\OneDrive\Desktop\create-social-network-master\api\node_modules\@apollographql\graphql-upload-8-fork\node_modules\fs-capacitor\lib\index.js:90:11)
    at _openReadFs (internal/fs/streams.js:138:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (C:\Users\maxau\OneDrive\Desktop\create-social-network-master\api\node_modules\@apollographql\graphql-upload-8-fork\node_modules\fs-capacitor\lib\index.js:90:11)
    at _openReadFs (internal/fs/streams.js:138:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
    at ReadStream.open (C:\Users\maxau\OneDrive\Desktop\create-social-network-master\api\node_modules\@apollographql\graphql-upload-8-fork\node_modules\fs-capacitor\lib\index.js:90:11)
    at _openReadFs (internal/fs/streams.js:138:12)
    at ReadStream.<anonymous> (internal/fs/streams.js:131:3)
    at ReadStream.deprecated [as open] (internal/util.js:89:15)
[nodemon] app crashed - waiting for file changes before starting...

Please say me how i can fix this

**Comment by DimiMikadze** [comment]
Hi, I'm closing this issue since we uploaded a new project to this repository. The old one is located here: https://github.com/DimiMikadze/create-social-network-old.
