### ISSUE TITLE
Heroku api Refused to load the image on production

### ISSUE THREAD

**Issue by cichy** [DimiMikadze/orca#42]
Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback. Refused to load the image 'https://myapp.herokuapp.com/favicon.ico' because it violates the following.

Need help on how to deal with this I've tried many things thus deployment process is very slow if you don't mind please point me in the right direction. Thank you.

**Comment by DimiMikadze** [comment]
@cichy when opening an issue please respect issue template and try to explain your problem.

You are having an issue with Heroku, because you've made some changes either in the app or in the Heroku configuration, which you are not explaining and unfortunately without this information I can't help you.

API deployment is pretty straightforward and is explained in here: https://github.com/DimiMikadze/create-social-network/tree/master/api#api-deployment-to-heroku

**Comment by cichy** [comment]
**Describe the topic**
Still facing this issue. I share it on yu :) link below
API doesn't work on production => https://createsocial.herokuapp.com
Refused to load the image 'https://myapp.herokuapp.com/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
createsocial.herokuapp.com/:1 Failed to load resource: the server responded with a status of 404 (Not Found)

FRONTEND => https://createsocial.netlify.com
client.js:649 Mixed Content: The page at 'https://createsocial.netlify.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://createsocial.herokuapp.com/graphql'. This request has been blocked; this endpoint must be available over WSS.
e.connect @ client.js:649
e @ client.js:225
t @ bundle.esm.js:14
(anonymous) @ apollo-client.js:73
94 @ index.js:25
f @ (index):1
67 @ background.jpg:1
f @ (index):1
a @ (index):1
e @ (index):1
(anonymous) @ main.6f9cda56.chunk.js:1
client.js:649 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at e.connect (https://createsocial.netlify.com/static/js/2.5192c1e6.chunk.js:1:234756)
    at new e (https://createsocial.netlify.com/static/js/2.5192c1e6.chunk.js:1:228471)
    at new t (https://createsocial.netlify.com/static/js/2.5192c1e6.chunk.js:1:267646)
    at https://createsocial.netlify.com/static/js/main.6f9cda56.chunk.js:1:158672
    at Module.94 (https://createsocial.netlify.com/static/js/main.6f9cda56.chunk.js:1:159069)
    at f (https://createsocial.netlify.com/:1:970)
    at Object.67 (https://createsocial.netlify.com/static/js/main.6f9cda56.chunk.js:1:284)
    at f (https://createsocial.netlify.com/:1:970)
    at a (https://createsocial.netlify.com/:1:839)
    at Array.e [as push] (https://createsocial.netlify.com/:1:702)


A clear and concise description of what the topic is.
Production failure => API favicion CSP violation, FRONTEND websocket
**Your suggestions for this topic**

**Code snippets**
https://github.com/cichy/create-social-network

**Additional context**
HEROKU LOG

Add any other context about the problem here.
heroku logs --tail
2020-03-30T12:18:54.356226+00:00 app[api]: Initial release by user myemail
2020-03-30T12:18:54.356226+00:00 app[api]: Release v1 created by user myemail
2020-03-30T12:18:54.464046+00:00 app[api]: Enable Logplex by user myemail
2020-03-30T12:18:54.464046+00:00 app[api]: Release v2 created by user myemail
2020-03-30T12:19:21.109111+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=createsocial.herokuapp.com request_id=9d713eb
a-76f1-42e1-aeb7-021403717bee fwd="80.49.170.60" dyno= connect= service= status=502 bytes= protocol=https
2020-03-30T12:19:21.414880+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=createsocial.herokuapp.com request
_id=71ed8701-4456-4932-9b45-da4f3bc97f52 fwd="80.49.170.60" dyno= connect= service= status=502 bytes= protocol=https
2020-03-30T12:27:21.243513+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=createsocial.herokuapp.com request_id=5af48ea
e-75f1-4c9f-b8b4-c16ed5db60db fwd="80.49.170.60" dyno= connect= service= status=502 bytes= protocol=https
2020-03-30T12:27:21.456860+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=createsocial.herokuapp.com request
_id=eb5bab21-2b18-4cea-af7a-c01480da0828 fwd="80.49.170.60" dyno= connect= service= status=502 bytes= protocol=https
2020-03-30T12:55:01.809213+00:00 app[api]: Release v3 created by user myemail
2020-03-30T12:55:01.809213+00:00 app[api]: Set API_PORT config vars by user myemail
2020-03-30T12:55:10.298948+00:00 app[api]: Set FRONTEND_URL config vars by user myemail
2020-03-30T12:55:10.298948+00:00 app[api]: Release v4 created by user myemail
2020-03-30T12:55:20.248639+00:00 app[api]: Release v5 created by user myemail
2020-03-30T12:55:20.248639+00:00 app[api]: Set MONGO_URL config vars by user myemail
2020-03-30T12:55:37.678803+00:00 app[api]: Release v6 created by user myemail
2020-03-30T12:55:37.678803+00:00 app[api]: Set SECRET config vars by user myemail
2020-03-30T12:55:44.424952+00:00 app[api]: Release v7 created by user myemail
2020-03-30T12:55:44.424952+00:00 app[api]: Set CLOUDINARY_CLOUD_NAME config vars by user myemail
2020-03-30T12:55:50.717433+00:00 app[api]: Set CLOUDINARY_API_KEY config vars by user myemail
2020-03-30T12:55:50.717433+00:00 app[api]: Release v8 created by user myemail
2020-03-30T12:55:57.027235+00:00 app[api]: Set CLOUDINARY_SECRET config vars by user myemail
2020-03-30T12:55:57.027235+00:00 app[api]: Release v9 created by user myemail
2020-03-30T12:56:11.596912+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/" host=createsocial.herokuapp.com request_id=4c42171
d-61f8-4001-8c82-1b6b1f4b9e47 fwd="80.49.170.60" dyno= connect= service= status=502 bytes= protocol=https
2020-03-30T12:56:12.015008+00:00 heroku[router]: at=info code=H81 desc="Blank app" method=GET path="/favicon.ico" host=createsocial.herokuapp.com request
_id=2a2abd92-1817-43a8-a6c2-86985ccabcc0 fwd="80.49.170.60" dyno= connect= service= status=502 bytes= protocol=https
2020-03-30T12:59:36.000000+00:00 app[api]: Build started by user myemail
2020-03-30T12:59:38.000000+00:00 app[api]: Build failed -- check your build output: https://dashboard.heroku.com/apps/289f330a-7bf1-47ea-af2b-d5a72cb566e
f/activity/builds/792adc4d-ec7a-4e2a-954e-cbb82c1a1fa0
2020-03-30T13:00:06.000000+00:00 app[api]: Build started by user myemail
2020-03-30T13:00:07.000000+00:00 app[api]: Build failed -- check your build output: https://dashboard.heroku.com/apps/289f330a-7bf1-47ea-af2b-d5a72cb566e
f/activity/builds/c82e09dc-b13e-48a3-9d59-04bd8fee7d63
2020-03-30T13:00:56.000000+00:00 app[api]: Build started by user myemail
2020-03-30T13:01:26.714631+00:00 app[api]: Deploy 880f6638 by user myemail
2020-03-30T13:01:26.731272+00:00 app[api]: Scaled to web@1:Free by user myemail
2020-03-30T13:01:26.714631+00:00 app[api]: Release v10 created by user myemail
2020-03-30T13:01:28.000000+00:00 app[api]: Build succeeded
2020-03-30T13:01:36.312170+00:00 heroku[web.1]: State changed from starting to up
2020-03-30T13:01:36.025266+00:00 app[web.1]: (node:4) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be remov
ed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
2020-03-30T13:01:36.026424+00:00 app[web.1]: server ready at http://localhost:4598/graphql
2020-03-30T13:01:36.026507+00:00 app[web.1]: Subscriptions ready at ws://localhost:4598/graphql
2020-03-30T13:01:36.072552+00:00 app[web.1]: (node:4) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
2020-03-30T13:01:36.073498+00:00 app[web.1]: DB connected
2020-03-30T13:01:51.148383+00:00 heroku[router]: at=info method=GET path="/" host=createsocial.herokuapp.com request_id=5fc2ca82-ab20-4ee8-952a-0df567cb74ba fwd="80.49.170.60" dyno=web.1 connect=1ms service=15ms status=404 bytes=500 protocol=https

Additional content on YouTube
API starts at 7:30.
https://www.youtube.com/watch?v=tlKEo7XxivM
