### ISSUE TITLE
Playground => Server cannot be reached

### ISSUE THREAD

**Issue by cichy** [DimiMikadze/orca#43]
**Describe the bug**
Dev mode:
App works but a playground server can't be reached.

FRONTEND LOG:
[1] Note that the development build is not optimized.
[1] To create a production build, use npm run build.
[1] 
[0] (node:4386) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/../api/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /../api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/../api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/../api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/..api/node_modules/apollo-server-core/dist/ApolloServer.js:450:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/../api/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:94:5)
[0] (node:4386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[0] (node:4386) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/Users/jarek/Projects/psyh/api/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /Users/jarek/Projects/psyh/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/jarek/Projects/psyh/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/jarek/Projects/psyh/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/jarek/Projects/psyh/api/node_modules/apollo-server-core/dist/ApolloServer.js:450:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/jarek/Projects/psyh/api/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:94:5)
[0] (node:4386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[0] (node:4386) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/Users/jarek/Projects/psyh/api/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /Users/jarek/Projects/psyh/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/../api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/../api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/../api/node_modules/apollo-server-core/dist/ApolloServer.js:450:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/../api/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:94:5)
[0] (node:4386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**System**
Browser version: 80.0.3987.149 (Official Build) (64-bit)
Node.js version: v12.14.1
NPM or Yarn version: 6.14.3
Operating system:
Version 80.0.3987.149 (Official Build) (64-bit)

**Steps to reproduce**
1. npx create-social-network myapp
2. npm start from root folder
3. open 'http://localhost:4000/graphql' in browser

**Expected behavior**
connect to graphql playground

(either PORT or async function with wrong syntax)

**Actual behavior**
PLAYGROUND LOG:
"error": "Failed to fetch schema. Please check your connection"

Failed to load resource: net::ERR_EMPTY_RESPONSE
TypeError: Failed to fetch

Will reproduce it later

**Comment by anishagg17** [comment]
@DimiMikadze  i too am facing same problem , how to resolve this error?

**Comment by Arif1951995** [comment]
@DimiMikadze  facing the same issue . how to resolve?
