### ISSUE TITLE
UnhandledPromiseRejectionWarning error on npm start

### ISSUE THREAD

**Issue by lane711** [DimiMikadze/orca#88]
Hello, I am attempting to setup a new site and getting this error on npm start:

npm start

> famlu-app-mern@1.0.0 start /Users/lanecampbell/Dev/famlu/famlu-app-mern
> concurrently "npm run start:api" "npm run start:frontend"

[1] 
[1] > famlu-app-mern@1.0.0 start:frontend /Users/lanecampbell/Dev/famlu/famlu-app-mern
[1] > npm start --prefix frontend
[1] 
[0] 
[0] > famlu-app-mern@1.0.0 start:api /Users/lanecampbell/Dev/famlu/famlu-app-mern
[0] > npm start --prefix api
[0] 
[1] 
[1] > famlu-app-mern-frontend@1.0.0 start /Users/lanecampbell/Dev/famlu/famlu-app-mern/frontend
[1] > react-scripts start
[1] 
[0] 
[0] > famlu-app-mern-api@1.0.0 start /Users/lanecampbell/Dev/famlu/famlu-app-mern/api
[0] > nodemon index.js
[0] 
[0] [nodemon] 2.0.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node index.js`
[1] ℹ ｢wds｣: Project is running at http://10.0.0.181/
[1] ℹ ｢wds｣: webpack output is served from 
[1] ℹ ｢wds｣: Content not from webpack is served from /Users/lanecampbell/Dev/famlu/famlu-app-mern/frontend/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1] 
[0] server ready at http://localhost:4000/graphql
[0] Subscriptions ready at ws://localhost:4000/graphql
[0] (node:40011) UnhandledPromiseRejectionWarning: JsonWebTokenError: invalid algorithm
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:121:19
[0]     at getSecret (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:90:14)
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:94:10)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:16:10)
[0]     at SubscriptionServer.onConnect (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:57:30)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/subscriptions-transport-ws/dist/server.js:123:47
[0]     at new Promise (<anonymous>)
[0]     at WebSocket.<anonymous> (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/subscriptions-transport-ws/dist/server.js:121:57)
[0]     at WebSocket.emit (events.js:315:20)
[0]     at WebSocket.EventEmitter.emit (domain.js:483:12)
[0]     at Receiver.receiverOnMessage (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/subscriptions-transport-ws/node_modules/ws/lib/websocket.js:720:20)
[0]     at Receiver.emit (events.js:315:20)
[0]     at Receiver.EventEmitter.emit (domain.js:483:12)
[0]     at Receiver.dataMessage (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/subscriptions-transport-ws/node_modules/ws/lib/receiver.js:414:14)
[0] (node:40011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[0] (node:40011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] DB connected
[1] Compiled successfully!
[1] 
[1] You can now view famlu-app-mern-frontend in the browser.
[1] 
[1]   Local:            http://localhost:3000
[1]   On Your Network:  http://10.0.0.181:3000
[1] 
[1] Note that the development build is not optimized.
[1] To create a production build, use npm run build.
[1] 
[0] (node:40011) UnhandledPromiseRejectionWarning: JsonWebTokenError: invalid algorithm
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:121:19
[0]     at getSecret (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:90:14)
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:94:10)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:546:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0] (node:40011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[0] (node:40011) UnhandledPromiseRejectionWarning: JsonWebTokenError: invalid algorithm
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:121:19
[0]     at getSecret (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:90:14)
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:94:10)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:16:10)
[0]     at SubscriptionServer.onConnect (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:57:30)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/subscriptions-transport-ws/dist/server.js:123:47
[0]     at new Promise (<anonymous>)
[0]     at WebSocket.<anonymous> (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/subscriptions-transport-ws/dist/server.js:121:57)
[0]     at WebSocket.emit (events.js:315:20)
[0]     at WebSocket.EventEmitter.emit (domain.js:483:12)
[0]     at Receiver.receiverOnMessage (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/subscriptions-transport-ws/node_modules/ws/lib/websocket.js:720:20)
[0]     at Receiver.emit (events.js:315:20)
[0]     at Receiver.EventEmitter.emit (domain.js:483:12)
[0]     at Receiver.dataMessage (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/subscriptions-transport-ws/node_modules/ws/lib/receiver.js:414:14)
[0] (node:40011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[0] (node:40011) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:546:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0] (node:40011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[0] (node:40011) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:546:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0] (node:40011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
[0] (node:40011) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:546:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0] (node:40011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
[0] (node:40011) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:546:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0] (node:40011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
[0] (node:40011) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/jsonwebtoken/verify.js:53:17)
[0]     at /Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/lanecampbell/Dev/famlu/famlu-app-mern/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:546:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/lanecampbell/Dev/famlu/famlu-app-mern/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0] (node:40011) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)

**Comment by DimiMikadze** [comment]
Hi @lane711, I'm not able to understand/reproduce your issue. Try running frontend and API separately with `npm start`. If It won't help describe the bug in more detail by respecting the bug report template.

**Comment by lane711** [comment]
This happens on the api project. I'm afraid there aren't any details beyond the stack trace as this happens at startup. 

I tried on another system and everything works fine. 

I tried with earlier versions of node and that didn't help either, but it does appear to be something related to my local setup/system. I'm running Catalina. I'll report back if I am able to resolve

**Comment by Shiba-Kar** [comment]
*PS C:\Programming\Node.js\create-social-network> npm run start:api*


> social-network@1.0.0 start:api C:\Programming\Node.js\create-social-network
> npm start --prefix api


> social-network-api@1.0.0 start C:\Programming\Node.js\create-social-network\api
> nodemon index.js

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json  
[nodemon] starting `node index.js`
server ready at http://localhost:4000/graphql
Subscriptions ready at ws://localhost:4000/graphql
DB connected
(node:11896) UnhandledPromiseRejectionWarning: JsonWebTokenError: jwt must be provided
    at Proxy.module.exports (C:\Programming\Node.js\create-social-network\api\node_modules\jsonwebtoken\verify.js:53:17)
    at C:\Programming\Node.js\create-social-network\api\utils\apollo-server.js:17:32
    at new Promise (<anonymous>)
    at checkAuthorization (C:\Programming\Node.js\create-social-network\api\utils\apollo-server.js:16:10)
    at ApolloServer.context (C:\Programming\Node.js\create-social-network\api\utils\apollo-server.js:45:28)
    at ApolloServer.<anonymous> (C:\Programming\Node.js\create-social-network\api\node_modules\apollo-server-core\dist\ApolloServer.js:546:38)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Programming\Node.js\create-social-network\api\node_modules\apollo-server-core\dist\ApolloServer.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.

*This error comes when I navigate to http://localhost:4000/graphql*

**Comment by DimiMikadze** [comment]
Hi @lane711 were you able to fix this issue on your end?

**Comment by lane711** [comment]
Hi @DimiMikadze , I just tried again with a new folder and get the same error. Again I think this is likely an issue with Catalina. Do you have access to Catalina or is anyone that has tried on Catalina?

Here is the full trace:

yarn start
yarn run v1.22.4
$ concurrently "npm run start:api" "npm run start:frontend"
[0] npm WARN lifecycle The node binary used for scripts is /var/folders/vf/yt5fxk2525d1hkc39qkjdnrw0000gn/T/yarn--1608482539736-0.5270700606619265/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[1] npm WARN lifecycle The node binary used for scripts is /var/folders/vf/yt5fxk2525d1hkc39qkjdnrw0000gn/T/yarn--1608482539736-0.5270700606619265/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[0] 
[0] > my-network@1.0.0 start:api /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network
[0] > npm start --prefix api
[0] 
[1] 
[1] > my-network@1.0.0 start:frontend /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network
[1] > npm start --prefix frontend
[1] 
[0] npm WARN lifecycle The node binary used for scripts is /var/folders/vf/yt5fxk2525d1hkc39qkjdnrw0000gn/T/yarn--1608482539736-0.5270700606619265/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[0] 
[0] > my-network-api@1.0.0 start /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api
[0] > nodemon index.js
[0] 
[1] npm WARN lifecycle The node binary used for scripts is /var/folders/vf/yt5fxk2525d1hkc39qkjdnrw0000gn/T/yarn--1608482539736-0.5270700606619265/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[1] 
[1] > my-network-frontend@1.0.0 start /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/frontend
[1] > react-scripts start
[1] 
[0] [nodemon] 2.0.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node index.js`
[1] ℹ ｢wds｣: Project is running at http://192.168.1.131/
[1] ℹ ｢wds｣: webpack output is served from 
[1] ℹ ｢wds｣: Content not from webpack is served from /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/frontend/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1] 
[0] server ready at http://localhost:4000/graphql
[0] Subscriptions ready at ws://localhost:4000/graphql
[0] DB connected
[1] Compiled successfully!
[1] 
[1] You can now view my-network-frontend in the browser.
[1] 
[1]   Local:            http://localhost:3000
[1]   On Your Network:  http://192.168.1.131:3000
[1] 
[1] Note that the development build is not optimized.
[1] To create a production build, use npm run build.
[1] 
[0] (node:31407) UnhandledPromiseRejectionWarning: JsonWebTokenError: invalid algorithm
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:121:19
[0]     at getSecret (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:90:14)
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:94:10)
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/apollo-server-core/dist/ApolloServer.js:546:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0] (Use `node --trace-warnings ...` to show where the warning was created)
[0] (node:31407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[0] (node:31407) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] (node:31407) UnhandledPromiseRejectionWarning: JsonWebTokenError: invalid algorithm
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:121:19
[0]     at getSecret (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:90:14)
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:94:10)
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:16:10)
[0]     at SubscriptionServer.onConnect (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:57:30)
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/subscriptions-transport-ws/dist/server.js:123:47
[0]     at new Promise (<anonymous>)
[0]     at WebSocket.<anonymous> (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/subscriptions-transport-ws/dist/server.js:121:57)
[0]     at WebSocket.emit (events.js:315:20)
[0]     at WebSocket.EventEmitter.emit (domain.js:486:12)
[0]     at Receiver.receiverOnMessage (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/subscriptions-transport-ws/node_modules/ws/lib/websocket.js:720:20)
[0]     at Receiver.emit (events.js:315:20)
[0]     at Receiver.EventEmitter.emit (domain.js:486:12)
[0]     at Receiver.dataMessage (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/subscriptions-transport-ws/node_modules/ws/lib/receiver.js:414:14)
[0] (node:31407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[0] (node:31407) UnhandledPromiseRejectionWarning: JsonWebTokenError: invalid algorithm
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:121:19
[0]     at getSecret (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:90:14)
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:94:10)
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:16:10)
[0]     at ApolloServer.context (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:45:28)
[0]     at ApolloServer.<anonymous> (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/apollo-server-core/dist/ApolloServer.js:546:38)
[0]     at Generator.next (<anonymous>)
[0]     at fulfilled (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/apollo-server-core/dist/ApolloServer.js:5:58)
[0]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[0] (node:31407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[0] (node:31407) UnhandledPromiseRejectionWarning: JsonWebTokenError: invalid algorithm
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:121:19
[0]     at getSecret (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:90:14)
[0]     at Proxy.module.exports (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/jsonwebtoken/verify.js:94:10)
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:17:32
[0]     at new Promise (<anonymous>)
[0]     at checkAuthorization (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:16:10)
[0]     at SubscriptionServer.onConnect (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/api/utils/apollo-server.js:57:30)
[0]     at /Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/subscriptions-transport-ws/dist/server.js:123:47
[0]     at new Promise (<anonymous>)
[0]     at WebSocket.<anonymous> (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/subscriptions-transport-ws/dist/server.js:121:57)
[0]     at WebSocket.emit (events.js:315:20)
[0]     at WebSocket.EventEmitter.emit (domain.js:486:12)
[0]     at Receiver.receiverOnMessage (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/subscriptions-transport-ws/node_modules/ws/lib/websocket.js:720:20)
[0]     at Receiver.emit (events.js:315:20)
[0]     at Receiver.EventEmitter.emit (domain.js:486:12)
[0]     at Receiver.dataMessage (/Users/lanecampbell/Dev/famlu/csn-no-fork/my-network/node_modules/subscriptions-transport-ws/node_modules/ws/lib/receiver.js:414:14)
[0] (node:31407) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
